// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const radii = {
 "circle": "100px",
 "badges": "22px",
 "rounded": "4px",
 "hard": "0px",
 "card": "12px",
 "field": "8px",
} as const

export default radii;